### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ever4cyth** [lkrippahl/Open-Chemera#1]
Could you please help with this error?

compile Lazarus from source on ubuntu system,
after press F9,

Compile Project, Target: chemera: Exit code 1, Errors: 1, Warnings: 2, Hints: 5
basetypes.pas(910,3) Note: Local variable "ixs" is assigned but never used
basetypes.pas(926,3) Note: Local variable "ixs" is assigned but never used
stringutils.pas(282,7) Warning: Symbol "DecimalSeparator" is deprecated
oclconfiguration.pas(97,19) Warning: Symbol "DecimalSeparator" is deprecated
oglform.pas(480,9) Note: Local variable "a" not used
displayobjects.pas(85,9) Note: Local variable "f" not used
displayobjects.pas(202,3) Note: Local variable "al" not used
molfit.pas(20,43) Fatal: Cannot find unit alignment used by molfit.

**Comment by lkrippahl** [comment]
Hi,

Sorry for the delay, and thank you for your patience. There were a few units not being copied to the git repository; I think it's all fixed now.

Best regards,
L
